/*
DROP TABLE ofo;
DROP TABLE diak;
DROP TABLE  Osztaly;

CREATE TABLE Osztaly(
    Nev VARCHAR(25),
    ID INT PRIMARY KEY
);

CREATE TABLE diak(
    Nev VARCHAR(25),
    Kor NUMBER(3),
    osztaly_ID INT,
    FOREIGN KEY(osztaly_ID) REFERENCES Osztaly(ID)
);


ALTER TABLE Osztaly
ADD letszam INT;

ALTER TABLE Osztaly
ADD CONSTRAINT CHK_age CHECK (letszam>15);

CREATE TABLE ofo(
    Nev VARCHAR(25),
    osztaly_ID INT,
    FOREIGN KEY(osztaly_ID) REFERENCES Osztaly (ID)
);

ALTER TABLE osztaly
MODIFY Nev VARCHAR(4);

ALTER TABLE Osztaly
RENAME COLUMN Nev TO OsztalyNev
*/

DROP TABLE LOOT;
DROP TABLE POI;
DROP TABLE MAP;

CREATE TABLE MAP(
    Nev VARCHAR(20),
    ID INT PRIMARY KEY
);
CREATE TABLE POI(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    MAP_ID INT,
    FOREIGN KEY(MAP_ID) REFERENCES MAP(ID)
);
CREATE TABLE LOOT(
    Nev VARCHAR(20),
    ID INT PRIMARY KEY,
    Rarity VARCHAR(20) DEFAULT 'Common',
    POI_ID INT,
    FOREIGN KEY(POI_ID) REFERENCES POI(ID)
);