/*
DROP TABLE FAN;
DROP TABLE MARKA;
CREATE TABLE MARKA(
    ID INT PRIMARY KEY,
    NÉV VARCHAR(20),
    LOKÁCIÓ VARCHAR(20)
);
CREATE TABLE FAN(
    ID INT, 
    NÉV VARCHAR(20),
    MÁRKAID INT,
    FOREIGN KEY (MÁRKAID) REFERENCES MARKA(ID)
);

INSERT INTO MARKA(ID, NÉV, LOKÁCIÓ) VALUES (1, 'PHILIPS', 'Miskolc');
INSERT INTO MARKA(ID, NÉV, LOKÁCIÓ) VALUES (2, 'Samsung', 'Budapest');
INSERT INTO MARKA(ID, NÉV, LOKÁCIÓ) VALUES (3, 'LG', 'Győr');
INSERT INTO MARKA(ID, NÉV, LOKÁCIÓ) VALUES (4, 'Sony', 'Debrecen');

INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (1, 'John Doe', 1);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (2, 'Jane Smith', 2);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (3, 'Bob Brown', 3);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (4, 'Alice Green', 4);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (5, 'Charlie White', 5);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (6, 'Eve Black', 6);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (7, 'Frank Yellow', 7);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (8, 'Grace Blue', 8);
INSERT INTO FAN(ID, NÉV, MÁRKAID) VALUES (9, 'Henry Violet', 9);
SELECT * FROM FAN;

DELETE FROM FAN WHERE ID = 3;

SELECT * FROM FAN;

UPDATE FAN SET NÉV = 'Cinege' WHERE ID = 2;

SELECT * FROM FAN;
SELECT * FROM FAN, MARKA WHERE FAN.MÁRKAID = MARKA.ID;

SELECT * FROM FAN INNER JOIN MARKA
ON FAN.MÁRKAID = MARKA.ID
WHERE MARKA.NÉV LIKE 'PHILIPS';
*/
-- Melyik ventillátorokat gyártják Miskolcon?


SELECT * FROM MARKA WHERE MARKA.LOKÁCIÓ LIKE 'Miskolc';


-- Melyik ventillátorokat gyárjta olyan gyártó, akinek van p a nevében

SELECT * FROM FAN WHERE FAN.NÉV LIKE '' ;
